### ISSUE TITLE
Wybrać i udokumentować strategię oceny ryzyka

### ISSUE THREAD

**Issue by NoxMar** [NoxMar/diet-penguin#10]

**Comment by myszkowskilukasz** [comment]
Jako strategię oceny ryzyka do projektu proponuję wykres spalania ryzyka. Uzasadnienie tego wyboru oraz pierwszą wersję dokumentacji przedstawię w następnym komentarzu

**Comment by myszkowskilukasz** [comment]
Wybraną przez nas metodą przeprowadzenia analizy ryzyka jest **wykres spalania ryzyka**.

Jest to praktyka znana przy zwinnym projektowaniu oprogramowania, która pozwala zespołowi deweloperskiemu na śledzenie ekspozycji projektu na ryzyko w miarę powstawania kolejnych iteracji.

Zastosowanie tego podejścia wymaga od nas wcześniejszego zdefiniowania danych wejściowych takich jak:

- Lista zidentyfikowanych przez nas ryzyk,
- Oszacowane prawdopodobieństwo ich wystąpienia,
- Oszacowana strata (wyrażona będzie przez nas w dniach),

Jako wynik powyższych rozważań, otrzymamy tzw. **ekspozycję**, która jest iloczynem oszacowanego prawdopodobieństwa oraz straty.

### Lista potencjalnych ryzyk w projekcie:

1. **Problemy z integrowalnością zewnętrznych serwisów** - ponieważ aplikacja będzie musiała integrować się z aplikacją dekstopową używaną przez firmę do zarządzania wizytami klientów, mogą pojawić się problemy np. z API,
2. **Problemy z ochroną danych i prywatnością użytkowników** - konieczne będzie przestrzeganie regulacji dotyczących ochrony danych (np. RODO, GDPR) oraz zapewnienie bezpieczeństwa danych użytkowników. W związku z tym należy wdrożyć odpowiednie mechanizmy zabezpieczeń, przeprowadzić audyty i przeszkolić pracowników z zakresu ochrony danych osobowych,
3. **Problemy z interfejsem użytkownika** - jeśli interfejs użytkownika nie będzie intuicyjny lub trudny do obsługi, pilotażowa grupa użytkowników, która będzie testowała prototyp może mieć negatywne wrażenia z uzywania aplikacji; z kolei niedostosowanie się do zaleceń i aktualnego wizerunku (barw) firmy może doprowadzić do sytuacji, w której to już sam klient nie zaakceptuje interfejsu aplikacji w danej postaci i konieczne będą zmiany,
4. **Problemy z wydajnością aplikacji** - wraz z rozwojem produktu oraz rozrostem firmy klienta, teoretycznie możliwe są spadki wydajności aplikacji, związane z potencjalnie zwiększająca się liczbą użytkowników,
5. **Problemy z działaniem aplikacji na wszystkich OS** - do terminu oddania projektu zespołowi może zabraknąć czasu na sprawdzenie poprawności działania systemu we wszystkich dostępnych przeglądarkach, na wszystkich najpopularniejszych systemach operacyjnych,
6. **Problemy z dostarczoną dokumentacją** - klient może stwierdzić, że opracowana przez zespół projektowy dokumentacja oraz intrukcja użytkownika są niewystarczające do przeszkolenia pracowników i klientów; może wymagać więcej dokumentów opisujących działanie systemu.

### Dane do wykresu spalania ryzyka - Iteracja 0

| Ryzyko                                                | Prawdopodobieństwo (w %) | Strata (w dniach) | Ekspozycja |
| ----------------------------------------------------- | ------------------------ | ----------------- | ---------- |
| Problemy z integrowalnością zewnętrznych serwisów     | 20                       | 15                | 3          |
| Problemy z ochroną danych i prywatnością użytkowników | 30                       | 20                | 6          |
| Problemy z interfejsem użytkownika                    | 50                       | 4                 | 2          |
| Problemy z wydajnością aplikacji                      | 10                       | 10                | 1          |
| Problemy z działaniem aplikacji na wszystkich OS      | 40                       | 5                 | 2          |
| Problemy z dostarczoną dokumentacją                   | 25                       | 20                | 5          |
| Ekspozycja                                            |                          |                   | 19         |

Tabele z danymi z kolejnych iteracji przechowywać będziemy w repozytorium na githubie, ponieważ pozwoli to na automatyczne wygenerowanie wykresu na późniejszym etapie projektu.

### Wykres spalania ryzyka

Zestawienia podobne do powyższego będą przez nas tworzone dla każdej iteracji projektu. Wyliczona w ten sposób ekspozycja pozwala bowiem na wyznaczenie linii spalania między danymi iteracjami, a także wizualne porównanie jej do przyjętej linii idealnego spalania.

Ekspozycja na ryzyko powinna oczywiście, wraz z postępem w projekcie, wykazywać tendencję spadkową. W razie gdy tak się nie dzieje lub widoczne są duże odstępstwa między linią ekspozycji a idealnym spalaniem, metoda analizy ryzyka umożliwia szybkie zareagowanie w miarę potrzeb.

Zdecydowaliśmy się użyć w nasznym projekcie właśnie tej metody oceny ryzyka, ze względu na jej wysoką użyteczność, estetyczny aspekt wizualny i łatwą dostępność wyników oceny ryzyka.

Źródła:  
[Jeden z artykułów udostępniony nam na moodle'u](https://wir.ue.wroc.pl/info/article/WUT047053e0812d4b8b81faaed65ad0c51d/)  
[Trochę starszy artykuł, na którym ten powyższy zdaje się bazować](https://www.mountaingoatsoftware.com/blog/managing-risk-on-agile-projects-with-the-risk-burndown-chart)

**Comment by myszkowskilukasz** [comment]
Proszę o wasz feedback. Jeśli będziemy zgodni, to w podobnej wersji wpis ten umieszczę w dokumentacji projektu (docx)

**Comment by NoxMar** [comment]
Pierwsze moje pytanie dotyczy się "iteracji". Przypominam, że w sumie nie robimy rozdzielonych iteracji, robiąc kanban. Moim zdaniem aktualizację ryzyk można robić "na bieżąco" w ramach edycji jednego dokumentu w repozytorium i potem dokonać ekstrakcji danych z historii repozytorium tego pliku dodając jako punkt każdy commit do repozytorium, który zmieniał ten plik.

Co do konkretnych ryzyk w tabeli wypowiem się jutro, choć wstępnie wyglądają racjonalnie. Rozważyłbym dodanie na początku czegoś związanego z wymaganiami od klienta, które będą zawarte w style guide. Jest on jeszcze nieustalony, a jego treść ma wpływ na ilość czasu potrzebnego na przygotowanie interfejsu użytkownika.

Dodatkowo warto by się zastanowić nad śledzeniem wartości ekspozycji i potencjalnym automatycznym jej liczeniem. W ramach pierwszego z tych problemów proponuję rozważyć następujące opcje:
1. Ekstrakcja z historii dokumentu zawierającego całą tabelę. Jeśli nie będzie on zbytnio złożony ekstrakcja tego będzie trywialna krótkim skryptem
2. Śledzenie wartości w osobnym pliku, którego śledzenie historii będzie jeszcze prostsze

Tworzenie wykresu myślę, że zrobimy ręcznie, ponieważ wydaje mi się, że automatyzacja tego to będzie "więcej szkody niż pożytku", biorąc pod uwagę ile to zajmie. Jeśli będziemy mieli więcej metryk, które będziemy chcieli śledzić "na bieżąco" w projekcie możemy rozważyć integrację instancji Grafany w nasz workflow. Względem integracji dla jednej wartości jestem przeciwny, ponieważ zwiększa to koszt czasowy utrzymania projektu, ponieważ trzeba będzie zarządzać tą instancją.

**Comment by myszkowskilukasz** [comment]
Zdaję sobie sprawę, że w Kanbanie nie ma iteracji jako takich. Przez iterację miałem w naszym przypadku na myśli np. pozytywne przejście User Story przez code review i zintegrowanie z główną gałęzią. Co myślisz o takim podejściu? 
Twoje podejście, w którym to commity zmieniające plik z repozytorium są takimi jakby iteracjami, też mi się podoba.

Jeśli chodzi o ryzyko związane z wymaganiami klienta, o którym wspomniałeś, to coś podobnego zawarłem w punkcie "Problemy z interfejsem użytkownika". Może wystarczyłaby więc ewentualna aktualizacja opisu tego ryzyka tak, by zawierała frazę "style guide"?

Zgadzam się, że potrzebujemy śledzić wartość ekspozycji. Jeśli czujesz się na siłach napisać skrypt, o którym mowa w 1., to nie widzę przeszkód. Natomiast najprościej byłoby chyba zrobić jakiś arkusz kalkulacyjny, dedykowany właśnie przechowywaniu i wyliczaniu tych wartości. Pozostaje kwestia jak wypełniać arkusz nowymi wartościami — ręcznie czy znowu próbować automatyzować?

Zgoda, automatyzację grafów odpuśćmy. Czas goni ;)

**Comment by NoxMar** [comment]
## Odpowiedź w kwestiach nie związanych z automatyzacją

Szczerze pull requesty też brzmią jak dobry pomysł, natomiast spodziewam się, że to w praktyce będzie równoważne (zmiany w tej tabeli nie powinny, moim zdaniem, występować często więcej niż raz na feature branch jeśli rozmiar user stories będzie odpowiedni). Dodatkowo nie jest to decyzja, którą musimy podejmować teraz i blokować na niej projekt.

W kwestii style guide i zawarcia go w punkcie "Problemy z interfejsem użytkownika" myślę, że zawsze można dać jakiś przypis, żeby nie musieć wydłużać nazwy tego ryzyka lub nie przeformułowywać tytułu by na siłę zawierał "style guide".

## Propozycja w kwestii automatyzacji z uzasadnieniem

Jak chodzi o skrypt i/lub arkusza kalkulacyjny to wydaje mi się, że zaszło drobne nieporozumienie z uwagi na to, że były poruszane 2 podobne kwestie, mianowicie:
1. Automatyzacja liczenia wartości ekspozycji
2. Śledzenie zmian wartości ekspozycji w celu przygotowania danych do wykresu

Moją propozycją jest do samego liczenia wartości ekspozycji użyć po prostu arkusza kalkulacyjnego, jak proponujesz, bo automatyzacja tego w samym repozytorium bez użycia zewnętrznych systemów byłaby stosunkowo skomplikowana. Rzuciłem to jako luźny pomysł/ewentualność jakby ktoś zobaczył sugestię i wpadł na pomysł jak to prosto technicznie zrobić.
Moja propozycja co do sposobu i "ilości automatyzacji" tego aspektu w tym projekcie jest następująca:
- Wartość ekspozycji (to o czym wspominam w 1.) liczona jest ręcznie przy użyciu arkusza kalkulacyjnego. Można to dodać jako opcjonalny krok DoD jeśli dana zmiana będzie miała wpływ na wartości, z których ta ekspozycja jest wyliczana.
- Napisać skrypt, który potem "przejdzie" historię głównej gałęzi repozytorium ekstrahując wartość ekspozycji dla każdego commitu, w którym edytowany jest plik zawierający tabelę do jakiegoś formatu wspieranego przez program do arkuszy kalkulacyjnych (najprościej będzie `.csv`)
- Na bazie tych danych w arkuszu kalkulacyjnym wykonać wykres (raz, nie w formie jakiegokolwiek regularnego zadania czy wymagania DoD) i zamieścić go w prezentacji

Rozwiązane to proponuję jako, moim zdaniem, odpowiednie połączenie automatyzacji, która ma sens (nie zajmuje nieproporcjonalnej ilości czasu z tą, którą oszczędza te kilka razy kiedy zostanie użyta) z nie blokowaniem projektu, ponieważ:
- nie blokuje śledzenia ekspozycji — możemy dodać do repozytorium w tym momencie tabelę spod nagłówka "Dane do wykresu spalania ryzyka — Iteracja 0" w tym momencie a skrypt napisać za miesiąc i nie stracimy żadnych danych
- nie wymaga tworzenia własnych, złożonych Github Actions
- nie wymaga za wiele pracy — napisanie tego skryptu oceniam na poniżej 1 godziny mojego czasu, którą dodatkowo można wykonać w dowolnym momencie projektu

## Podsumowanie

Myślę, że można ten FR **zamknąć** po wprowadzeniu w dokumentacji tabeli wspomnianej wcześniej w historii tego FR **z wprowadzeniem wyżej wspomnianego przypisu**. **Sugeruję natomiast dodania tego w osobnym pliku/sekcji**, a nie do żadnego z istniejących już plików w celu uproszczenia opisanego w drugim punkcie skryptu. Ten plik nie musi być ograniczony do tabeli (może spokojnie zawierać jej krótki opis itp. jeśli uznasz za stosowny) jednak dobrze by było, żeby **jego struktura była stosunkowo statyczna a zmiany dotyczyły możliwie tylko sytuacji, w których zmieniane są dane dotyczące oceny ryzyka**. Dodatkowo można w tym dokumencie opisać opcjonalną stopkę (jako pojęcie zgodne ze specyfikacją conventional commits) `BOT SKIP: true` dla commitów, które dotykają plików, które mogą mieć interakcje z narzędziami, jednak zawierają zmiany, które powinny przez te narzędzia zostać pominięte.
