### ISSUE TITLE
Ustalić szablon historyjki użytkownika

### ISSUE THREAD

**Issue by NoxMar** [NoxMar/diet-penguin#4]
Do zaczęcia ustalania konkretów historyjek użytkownika potrzebny jest nam konkretny szablon do ich zapisywania. Należy go, moim zdaniem, dodać do dokumentacji oraz jako szablon issue w GitHub.

- [x] Przygotowanie szablonu dla historyjki użytkownika w ramach dokumentacji
- [x] Dodanie przygotowanego szablonu jako szablonu "Issue" na platformie GitHub

**Comment by NoxMar** [comment]
Myślę, że do wymagań tego issue należałoby dodać:
- [ ]  krótko opisać utowrozne pola tego szablonu i ich znaczenie w ramach dokumentacji 
- [ ] opisać sposób łączenia historyjek użytkowników i epiców z nimi związanych

**Comment by myszkowskilukasz** [comment]
Żeby trochę skrócić pracę, proponuję utworzyć szablon historyjek użytkownika na podstawie [tego style guide'a](https://github.com/AlphaFounders/style-guide/blob/master/agile-user-story.md).

**Comment by NoxMar** [comment]
Brzmi jak dobra podstawa, zaadaptuję to do użycia Github Projects oraz przetłumaczę na polski i dodam gałąź z propozycją. Te adaptacje powinny, moim zdaniem, zawierać:
- Opis użycia pól (poprostu w tekście a tych, które są dostępne na widoku projektu)
- Próbę znalezienia czytelnego sposbu łączenia epiców w sposób widoczny na kanban boardzie

**Comment by NoxMar** [comment]
Zamknąłem przez przypadek, myślałem, że pracuję na repozytorium tesotwym, które miałem otwarte w karcie obok.

**Comment by NoxMar** [comment]
Szablon issue utworzony jest w ramach #18. W związku z ograniczeniem interfejsu graficznego GitHub (szczegóły opisane w #18). Ponieważ #18 realizuje ostatnie zadanie zintegrowanie go traktował będę jako zamkniecie tego issue.
