### ISSUE TITLE
Ustalić i stworzyć strukturę projektów

### ISSUE THREAD

**Issue by NoxMar** [NoxMar/diet-penguin#5]
Proponowana struktura projektów bazująca na Vertical Slice Architecture oraz projektowaniu zorientowanym na domenę (Domain Driven Design).

**Comment by NoxMar** [comment]
**WIP, tekst wymaga dokończenia jednak wstępne sugestie co do wyboru/pytania/komentarze mile widziane.**

Sugeruję wybranie jednej z poniższych sposobów organizacji solucji dla porjektów dotyczących API:
1. Clean Architecture
2. Vertical Slice Architecture
3. Połączenie tych architektur z wydzieloną warstwą domeny

## Porównanie 

### 1. Clean Architecture

![Clean architecture image from Uncle Bob's blog](https://blog.cleancoder.com/uncle-bob/images/2012-08-13-the-clean-architecture/CleanArchitecture.jpg)
W dużym skrócie każdy projekt należy do jednej z warstw i zależności między nimi mogą być tylko w kierunku "do wewnątrz" (use case-y zależą od logiki domeny, api zależy od use caseów itp.) 

[Dokłdniejsze wprowadzenie na blogu Roberta C. Martina](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html)

#### Zalety

- Jasna, czytelna separacja zagadnień (separation of concerns)
- Szybkie w wykonaniu testy (projekty z poszczególnych warstw mają stosunkowo mało zależności i są dość "lekkie", szczególnie projekt zawierający logikę domeny, na którym skupiona będzie duża część testów jednostkowych)
- (teoretycznie) Łatwa zmiana bibliotek i frameworków, od których zależą  konkretne projekty, ponieważ od siebie nawzajem zależą one przez abstrackje.

#### Wady

- Kod dotyczący jednej funkcjonalności znajduje się w wielu projektach. Spowalnia to nawigowanie po kodzie związanym z jedną funkcjonalnością.
- Duża ilość abstrakcji (ponieważ warstwy zależą od siebie przez abstrakcje wymagane jest wprowadzenie znaczącej ich ilości)
- W praktyce implemntacja prostszych funkcjonalności może wymagać nieproporcjonalnie dużo kodu aby nie naruszyć sztywno narzuconych granic warstw. Niektóre porstsze funkcjonalności nie muszą nawet wymagać wszystkich warstw.

### 2. Vertical Slice Architecture

[prosta wizualizacja struktury[(https://jimmybogardsblog.blob.core.windows.net/jimmybogardsblog/3/2018/Picture0030.png)

Tu projekty dzielone są z uwagi na fragmenty funkcjonalności, której dotyczą (np. wycinek dotyczący użytkowników, celów, spożywanych proudktów itp) a nie warstwę, do której należą. Architektura ta jest próbą wykorzystania dość oczywistego spotrzeżenia, że implemntacja jednej funkcjonalności z perspektywy użytkownika wymaga w praktycznie zawsze wielu (a często wszystkich) "warstwach" wyróżnianych w typowej architekturze warstwowej. A architekturze tej przykłada się uwagę do tego, żeby powiązania między tymi pionowymi wycinkami były możliwie małe i elastyczne (często tylko przez zdarzenia).

Zazwyczaj w tej architekturze stosuje się zazwyczaj również zależności "do wewnątrz" w klasycznej architekturze jednak nie **nie forsuje się ich przy użyciu osobnych projektów i zależności między nimi** (można przez testy architekturalne). Są to w tym przypadku **zależności pomiędzy typami a nie pakietami**. Celem takiego centralizacja kodu dotyczącego jednej funkcjonalności w "jednym miejscu" w projekcie upraszczając i przyspieszając pracę nad konkretną funkcjonalnością.

Typowe zależności między typami mogą być zobrazowane w następujący sposób:
![schemat typowych zależności w VSA](https://codeopinion.com/wp-content/uploads/2021/09/vsa2.png)

[Dokładniejsze wprowadzenie na blogu Code Opinion](https://codeopinion.com/restructuring-to-a-vertical-slice-architecture/)

#### Zalety

- Prostsza lokalizacja i szybsza praca nad kodem związanym z jedną, konkretną funkcjonalnością
- Zmniejszenie ilości zbędnych abstrakcji wymuszonych przez szytwne warstwy
- Podział na moduły względem funckjonalności umożliwiający proszą ekstrakcję funckjonalności do osobnej aplikacji (np. w celu wydzielenia jej jako mikrousługi) zmieniając implementację za fasadami komunikacji pomiędzy wycinkami bez potrzeby wprowadzania zmian do wycinków zależnych od ekstrachowanego.

#### Wady

**Comment by myszkowskilukasz** [comment]
Bardzo dobre i wyczerpujące porównanie. Merytorycznie nie mam zastrzeżeń. Pozwoliłem sobie jedynie poprawić kilka błędów językowych i logicznych, bo można będzie ten komentarz później wykorzystać w dokumentacji jako uzasadnienie naszego wyboru.

I wreszcie, zgadzam się z propozycją zastosowania w projekcie struktury VSA z wydzieloną logiką domeny.

Swój głos na tę opcję oddaję za pomocą emoji kciuka pod powyższym komentarzem. Czekam na jeszcze jeden głos za tą opcją, żeby zamknąć issue.

**Comment by NoxMar** [comment]
Dziękuję zarówno za edycję jak i za głos. Myślę, jednak, że wybranie architektury projektu nie powinno być równoważne zamknięciu tego issue a zmianie jego statusu na "TODO". Zwracam uwagę, że jej tytuł zawiera w sobie też stworzenie tej struktury. Ja progresję przez statusy tej issue widzę następująco:
1. `RFC` - dyskusja i  pojęcie przez zespół decyzji (czego jesteśmy blisko)
2. `Todo` - decyzje zostały podjęte i issue czeka aż ktoś się nią zajmie
3. `In Porgress` - utworzenie gałęzi roboczej, stworzenie w jej ramach struktury projektu i otwarcie PR
Postęp przez dalsze stany wydaje mi się oczywisty i związany z recenzją (`In Review`) i potencjalnym zintegrowaniem zmian z główną gałęzią (`Done`).
